# Generated by Django 5.2.8 on 2025-11-10 09:30

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv_dokumenta",
                    models.CharField(max_length=255, verbose_name="Naziv dokumenta"),
                ),
                (
                    "fajl",
                    models.FileField(
                        upload_to=core.models.master_template_upload_path,
                        verbose_name="Fajl",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Master Templejt Dokument",
                "verbose_name_plural": "Master Templejti Dokumenata",
            },
        ),
        migrations.CreateModel(
            name="Klijent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv klijenta"),
                ),
                (
                    "pib",
                    models.CharField(max_length=20, unique=True, verbose_name="PIB"),
                ),
                ("adresa", models.CharField(max_length=255, verbose_name="Adresa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Klijent",
                "verbose_name_plural": "Klijenti",
                "ordering": ["naziv"],
            },
        ),
        migrations.CreateModel(
            name="TipDokumenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Naziv tipa dokumenta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tip Dokumenta",
                "verbose_name_plural": "Tipovi Dokumenata",
            },
        ),
        migrations.CreateModel(
            name="ArhiviraniDokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fajl",
                    models.FileField(
                        upload_to=core.models.arhivirani_dokument_upload_path,
                        verbose_name="Arhivirani fajl",
                    ),
                ),
                (
                    "datum_arhiviranja",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum arhiviranja"
                    ),
                ),
                (
                    "originalni_dokument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.dokument",
                        verbose_name="Originalni master templejt",
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arhivirani_dokumenti",
                        to="core.klijent",
                        verbose_name="Klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arhivirani Dokument",
                "verbose_name_plural": "Arhivirani Dokumenti",
            },
        ),
        migrations.CreateModel(
            name="Kontakt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ime_i_prezime",
                    models.CharField(max_length=255, verbose_name="Ime i prezime"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email adresa"),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telefon"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "klijent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontakti",
                        to="core.klijent",
                        verbose_name="Klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontakt",
                "verbose_name_plural": "Kontakti",
            },
        ),
        migrations.CreateModel(
            name="PoslatiMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primaoci", models.TextField(verbose_name="Primaoci (To)")),
                (
                    "naslov",
                    models.CharField(max_length=255, verbose_name="Naslov email-a"),
                ),
                ("telo_poruke", models.TextField(verbose_name="Telo poruke")),
                (
                    "datum_slanja",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum slanja"
                    ),
                ),
                (
                    "posiljalac",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Posiljalac",
                    ),
                ),
                (
                    "prilozeni_dokumenti",
                    models.ManyToManyField(
                        related_name="poslati_mailovi",
                        to="core.arhiviranidokument",
                        verbose_name="Priloženi dokumenti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poslati Mail",
                "verbose_name_plural": "Poslati Mailovi",
            },
        ),
        migrations.AddField(
            model_name="dokument",
            name="tip_dokumenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.tipdokumenta",
                verbose_name="Tip dokumenta",
            ),
        ),
    ]
