# Generated by Django 5.2.8 on 2025-11-10 10:16

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KategorijaDokumenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Naziv kategorije"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorija Dokumenta",
                "verbose_name_plural": "Kategorije Dokumenata",
            },
        ),
        migrations.CreateModel(
            name="Klijent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=255, verbose_name="Naziv firme")),
                (
                    "pib",
                    models.CharField(max_length=20, unique=True, verbose_name="PIB"),
                ),
                (
                    "maticni_broj",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matični broj"
                    ),
                ),
                ("adresa", models.CharField(max_length=255, verbose_name="Adresa")),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("web_sajt", models.URLField(blank=True, verbose_name="Web sajt")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.klijent_logo_upload_path,
                        verbose_name="Logo firme",
                    ),
                ),
                (
                    "sifra_delatnosti",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Šifra delatnosti"
                    ),
                ),
                (
                    "broj_zaposlenih",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ukupan broj zaposlenih"
                    ),
                ),
                (
                    "broj_zaposlenih_povecan_rizik",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Broj zaposlenih sa povećanim rizikom"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aktivan", "Aktivan"),
                            ("Neaktivan", "Neaktivan"),
                            ("Arhiviran", "Arhiviran"),
                        ],
                        default="Aktivan",
                        max_length=20,
                        verbose_name="Status klijenta",
                    ),
                ),
                (
                    "datum_pocetka_saradnje",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum početka saradnje"
                    ),
                ),
                (
                    "odgovorna_osoba_bzr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Odgovorna osoba za BZR",
                    ),
                ),
                ("napomene", models.TextField(blank=True, verbose_name="Napomene")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Klijent",
                "verbose_name_plural": "Klijenti",
                "ordering": ["naziv"],
            },
        ),
        migrations.CreateModel(
            name="Kontakt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ime_i_prezime",
                    models.CharField(max_length=255, verbose_name="Ime i prezime"),
                ),
                (
                    "pozicija",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Pozicija u firmi"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email adresa"),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "mobilni",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mobilni telefon"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primarni kontakt"),
                ),
                ("napomene", models.TextField(blank=True, verbose_name="Napomene")),
                (
                    "klijent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontakti",
                        to="core.klijent",
                        verbose_name="Klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontakt",
                "verbose_name_plural": "Kontakti",
            },
        ),
        migrations.CreateModel(
            name="MasterTemplejt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv šablona"),
                ),
                (
                    "fajl",
                    models.FileField(
                        upload_to=core.models.master_template_upload_path,
                        verbose_name="Fajl templejta",
                    ),
                ),
                (
                    "verzija",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Verzija"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aktivan", "Aktivan"),
                            ("Arhiviran", "Arhiviran"),
                            ("U pripremi", "U pripremi"),
                        ],
                        default="Aktivan",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis i napomene")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kategorija",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.kategorijadokumenta",
                        verbose_name="Kategorija dokumenta",
                    ),
                ),
                (
                    "kreator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kreirani_templejti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="core.mastertemplejt",
                        verbose_name="Prethodna verzija",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Templejt",
                "verbose_name_plural": "Master Templejti",
            },
        ),
        migrations.CreateModel(
            name="KlijentskiDokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv dokumenta"),
                ),
                (
                    "fajl",
                    models.FileField(
                        upload_to=core.models.klijentski_dokument_upload_path,
                        verbose_name="Finalni fajl",
                    ),
                ),
                ("datum_izdavanja", models.DateField(verbose_name="Datum izdavanja")),
                (
                    "rok_vazenja",
                    models.DateField(blank=True, null=True, verbose_name="Rok važenja"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aktivan", "Aktivan"),
                            ("Istekao", "Istekao"),
                            ("Arhiviran", "Arhiviran"),
                        ],
                        default="Aktivan",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verzija",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Verzija dokumenta"
                    ),
                ),
                ("napomene", models.TextField(blank=True, verbose_name="Napomene")),
                (
                    "klijent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumenti",
                        to="core.klijent",
                        verbose_name="Klijent",
                    ),
                ),
                (
                    "kreirao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kreirani_klijentski_dokumenti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "odobrio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="odobreni_klijentski_dokumenti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master_templejt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mastertemplejt",
                        verbose_name="Originalni master templejt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Klijentski Dokument",
                "verbose_name_plural": "Klijentski Dokumenti",
            },
        ),
        migrations.CreateModel(
            name="OrganizacionaJedinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(
                        max_length=255, verbose_name="Naziv poslovne jedinice"
                    ),
                ),
                ("adresa", models.CharField(max_length=255, verbose_name="Adresa")),
                (
                    "broj_zaposlenih",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Broj zaposlenih u jedinici"
                    ),
                ),
                (
                    "rukovodilac",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Rukovodilac jedinice"
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizacione_jedinice",
                        to="core.klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizaciona Jedinica",
                "verbose_name_plural": "Organizacione Jedinice",
            },
        ),
        migrations.CreateModel(
            name="PoslatiMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primaoci", models.TextField(verbose_name="Primaoci (To)")),
                (
                    "naslov",
                    models.CharField(max_length=255, verbose_name="Naslov email-a"),
                ),
                ("telo_poruke", models.TextField(verbose_name="Telo poruke")),
                (
                    "datum_slanja",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum slanja"
                    ),
                ),
                (
                    "posiljalac",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Posiljalac",
                    ),
                ),
                (
                    "prilozeni_dokumenti",
                    models.ManyToManyField(
                        blank=True,
                        related_name="poslati_mailovi",
                        to="core.klijentskidokument",
                        verbose_name="Priloženi dokumenti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poslati Mail",
                "verbose_name_plural": "Poslati Mailovi",
            },
        ),
        migrations.CreateModel(
            name="SmtpSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_host", models.CharField(max_length=255)),
                ("email_port", models.IntegerField(default=587)),
                ("email_host_user", models.CharField(max_length=255)),
                ("email_host_password_encrypted", models.BinaryField()),
                ("email_use_tls", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smtp_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMTP Podešavanje",
                "verbose_name_plural": "SMTP Podešavanja",
            },
        ),
    ]
