# Generated by Django 5.2.8 on 2025-11-10 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_host", models.CharField(max_length=255)),
                ("email_port", models.IntegerField(default=587)),
                ("email_host_user", models.CharField(max_length=255)),
                ("email_host_password_encrypted", models.BinaryField()),
                ("email_use_tls", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smtp_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMTP Podešavanje",
                "verbose_name_plural": "SMTP Podešavanja",
            },
        ),
    ]
