# Generated by Django 5.2.8 on 2025-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplejt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv templejta"),
                ),
                (
                    "naslov",
                    models.CharField(max_length=255, verbose_name="Naslov (Subject)"),
                ),
                (
                    "telo",
                    models.TextField(
                        help_text="Koristite promenljive poput {klijent_naziv}, {datum}, {dokumenti}.",
                        verbose_name="Telo poruke",
                    ),
                ),
                (
                    "kategorija",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kategorija"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Templejt",
                "verbose_name_plural": "Email Templejti",
            },
        ),
    ]
