# Generated by Django 5.2.8 on 2025-11-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_emailtemplejt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zaposleni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=100, verbose_name="Ime")),
                ("prezime", models.CharField(max_length=100, verbose_name="Prezime")),
                (
                    "jmbg",
                    models.CharField(max_length=13, unique=True, verbose_name="JMBG"),
                ),
                (
                    "radno_mesto",
                    models.CharField(max_length=255, verbose_name="Radno mesto"),
                ),
                (
                    "povecan_rizik",
                    models.BooleanField(
                        default=False, verbose_name="Radno mesto sa povećanim rizikom"
                    ),
                ),
                ("datum_zaposlenja", models.DateField(verbose_name="Datum zaposlenja")),
                (
                    "status",
                    models.CharField(
                        choices=[("Aktivan", "Aktivan"), ("Neaktivan", "Neaktivan")],
                        default="Aktivan",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "strucna_sprema",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stručna sprema"
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaposleni",
                        to="core.klijent",
                    ),
                ),
                (
                    "organizaciona_jedinica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organizacionajedinica",
                        verbose_name="Organizaciona jedinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaposleni",
                "verbose_name_plural": "Zaposleni",
            },
        ),
        migrations.CreateModel(
            name="Obuka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip_obuke",
                    models.CharField(
                        choices=[
                            ("Inicijalna", "Inicijalna"),
                            ("Periodična", "Periodična"),
                            ("Vanredna", "Vanredna"),
                        ],
                        max_length=50,
                        verbose_name="Tip obuke",
                    ),
                ),
                ("datum_obuke", models.DateField(verbose_name="Datum obuke")),
                (
                    "datum_vazenja",
                    models.DateField(verbose_name="Datum važenja (naredna obuka)"),
                ),
                (
                    "sertifikat",
                    models.FileField(
                        blank=True, null=True, upload_to="sertifikati/obuke/"
                    ),
                ),
                (
                    "zaposleni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obuke",
                        to="core.zaposleni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obuka BZR",
                "verbose_name_plural": "Obuke BZR",
            },
        ),
        migrations.CreateModel(
            name="LZO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip_opreme",
                    models.CharField(max_length=255, verbose_name="Tip opreme"),
                ),
                ("datum_izdavanja", models.DateField(verbose_name="Datum izdavanja")),
                (
                    "kolicina",
                    models.PositiveIntegerField(default=1, verbose_name="Količina"),
                ),
                (
                    "rok_trajanja",
                    models.DateField(
                        blank=True, null=True, verbose_name="Rok trajanja opreme"
                    ),
                ),
                (
                    "razduzeno",
                    models.BooleanField(default=False, verbose_name="Razduženo"),
                ),
                (
                    "zaposleni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lzo_zaduzenja",
                        to="core.zaposleni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lična Zaštitna Oprema (LZO)",
                "verbose_name_plural": "Lična Zaštitna Oprema (LZO)",
            },
        ),
        migrations.CreateModel(
            name="LekarskiPregled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip_pregleda",
                    models.CharField(
                        choices=[
                            ("Prethodni", "Prethodni"),
                            ("Periodični", "Periodični"),
                        ],
                        max_length=50,
                        verbose_name="Tip pregleda",
                    ),
                ),
                ("datum_pregleda", models.DateField(verbose_name="Datum pregleda")),
                (
                    "naredni_pregled",
                    models.DateField(verbose_name="Datum narednog pregleda"),
                ),
                (
                    "sposoban",
                    models.BooleanField(
                        default=True, verbose_name="Zdravstveno sposoban"
                    ),
                ),
                (
                    "dokument",
                    models.FileField(
                        blank=True, null=True, upload_to="lekarski_pregledi/"
                    ),
                ),
                (
                    "zaposleni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lekarski_pregledi",
                        to="core.zaposleni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lekarski Pregled",
                "verbose_name_plural": "Lekarski Pregledi",
            },
        ),
    ]
