# Generated by Django 5.2.8 on 2025-11-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_zaposleni_obuka_lzo_lekarskipregled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oprema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv opreme"),
                ),
                (
                    "inventarski_broj",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Inventarski broj"
                    ),
                ),
                (
                    "serijski_broj",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Serijski broj"
                    ),
                ),
                (
                    "proizvodjac",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Proizvođač"
                    ),
                ),
                (
                    "datum_nabavke",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum nabavke"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("U funkciji", "U funkciji"),
                            ("Na servisu", "Na servisu"),
                            ("Van upotrebe", "Van upotrebe"),
                        ],
                        default="U funkciji",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oprema",
                        to="core.klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oprema za Rad",
                "verbose_name_plural": "Oprema za Rad",
            },
        ),
        migrations.CreateModel(
            name="PregledIspitivanje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip_pregleda",
                    models.CharField(
                        max_length=255, verbose_name="Tip pregleda/ispitivanja"
                    ),
                ),
                ("datum_pregleda", models.DateField(verbose_name="Datum pregleda")),
                (
                    "naredni_pregled",
                    models.DateField(verbose_name="Datum narednog pregleda"),
                ),
                (
                    "ovlascena_kuca",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ovlašćena kuća"
                    ),
                ),
                (
                    "nalaz",
                    models.CharField(
                        choices=[
                            ("Ispravan", "Ispravan"),
                            ("Neispravan", "Neispravan"),
                        ],
                        max_length=20,
                        verbose_name="Nalaz",
                    ),
                ),
                (
                    "strucni_nalaz_fajl",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="strucni_nalazi/",
                        verbose_name="Stručni nalaz (fajl)",
                    ),
                ),
                (
                    "oprema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pregledi",
                        to="core.oprema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregled i Ispitivanje",
                "verbose_name_plural": "Pregledi i Ispitivanja",
            },
        ),
    ]
