# Generated by Django 5.2.8 on 2025-11-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_oprema_pregledispitivanje"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspekcija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum_inspekcije", models.DateField(verbose_name="Datum inspekcije")),
                (
                    "inspektor",
                    models.CharField(
                        max_length=255, verbose_name="Inspektor (ime, institucija)"
                    ),
                ),
                ("nalaz", models.TextField(verbose_name="Nalazi i nedostaci")),
                (
                    "zapisnik",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="inspekcije_zapisnici/",
                        verbose_name="Zapisnik (fajl)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("U toku", "U toku"), ("Završeno", "Završeno")],
                        default="U toku",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspekcije",
                        to="core.klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspekcija",
                "verbose_name_plural": "Inspekcije",
            },
        ),
        migrations.CreateModel(
            name="PovredaNaRadu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum_povrede",
                    models.DateTimeField(verbose_name="Datum i vreme povrede"),
                ),
                (
                    "mesto",
                    models.CharField(max_length=255, verbose_name="Mesto incidenta"),
                ),
                ("opis", models.TextField(verbose_name="Opis povrede i okolnosti")),
                ("svedoci", models.TextField(blank=True, verbose_name="Svedoci")),
                (
                    "tezina_povrede",
                    models.CharField(
                        choices=[
                            ("Laka", "Laka"),
                            ("Teška", "Teška"),
                            ("Smrtna", "Smrtna"),
                            ("Kolektivna", "Kolektivna"),
                        ],
                        max_length=20,
                        verbose_name="Težina povrede",
                    ),
                ),
                (
                    "izvestaj",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="povrede_izvestaji/",
                        verbose_name="Izveštaj o povredi (fajl)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="U obradi", max_length=50, verbose_name="Status"
                    ),
                ),
                (
                    "zaposleni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="povrede",
                        to="core.zaposleni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Povreda na Radu",
                "verbose_name_plural": "Povrede na Radu",
            },
        ),
    ]
