# Generated by Django 5.2.8 on 2025-11-10 10:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_inspekcija_povredanaradu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalEmailTemplejt",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv templejta"),
                ),
                (
                    "naslov",
                    models.CharField(max_length=255, verbose_name="Naslov (Subject)"),
                ),
                (
                    "telo",
                    models.TextField(
                        help_text="Koristite promenljive poput {klijent_naziv}, {datum}, {dokumenti}.",
                        verbose_name="Telo poruke",
                    ),
                ),
                (
                    "kategorija",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kategorija"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Email Templejt",
                "verbose_name_plural": "historical Email Templejti",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInspekcija",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("datum_inspekcije", models.DateField(verbose_name="Datum inspekcije")),
                (
                    "inspektor",
                    models.CharField(
                        max_length=255, verbose_name="Inspektor (ime, institucija)"
                    ),
                ),
                ("nalaz", models.TextField(verbose_name="Nalazi i nedostaci")),
                (
                    "zapisnik",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Zapisnik (fajl)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("U toku", "U toku"), ("Završeno", "Završeno")],
                        default="U toku",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Inspekcija",
                "verbose_name_plural": "historical Inspekcije",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalKategorijaDokumenta",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "naziv",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Naziv kategorije"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Kategorija Dokumenta",
                "verbose_name_plural": "historical Kategorije Dokumenata",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalKlijent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("naziv", models.CharField(max_length=255, verbose_name="Naziv firme")),
                (
                    "pib",
                    models.CharField(db_index=True, max_length=20, verbose_name="PIB"),
                ),
                (
                    "maticni_broj",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Matični broj"
                    ),
                ),
                ("adresa", models.CharField(max_length=255, verbose_name="Adresa")),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("web_sajt", models.URLField(blank=True, verbose_name="Web sajt")),
                (
                    "logo",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Logo firme"
                    ),
                ),
                (
                    "sifra_delatnosti",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Šifra delatnosti"
                    ),
                ),
                (
                    "broj_zaposlenih",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ukupan broj zaposlenih"
                    ),
                ),
                (
                    "broj_zaposlenih_povecan_rizik",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Broj zaposlenih sa povećanim rizikom"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aktivan", "Aktivan"),
                            ("Neaktivan", "Neaktivan"),
                            ("Arhiviran", "Arhiviran"),
                        ],
                        default="Aktivan",
                        max_length=20,
                        verbose_name="Status klijenta",
                    ),
                ),
                (
                    "datum_pocetka_saradnje",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum početka saradnje"
                    ),
                ),
                (
                    "odgovorna_osoba_bzr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Odgovorna osoba za BZR",
                    ),
                ),
                ("napomene", models.TextField(blank=True, verbose_name="Napomene")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Klijent",
                "verbose_name_plural": "historical Klijenti",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalKlijentskiDokument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv dokumenta"),
                ),
                ("fajl", models.TextField(max_length=100, verbose_name="Finalni fajl")),
                ("datum_izdavanja", models.DateField(verbose_name="Datum izdavanja")),
                (
                    "rok_vazenja",
                    models.DateField(blank=True, null=True, verbose_name="Rok važenja"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aktivan", "Aktivan"),
                            ("Istekao", "Istekao"),
                            ("Arhiviran", "Arhiviran"),
                        ],
                        default="Aktivan",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verzija",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Verzija dokumenta"
                    ),
                ),
                ("napomene", models.TextField(blank=True, verbose_name="Napomene")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.klijent",
                        verbose_name="Klijent",
                    ),
                ),
                (
                    "kreirao",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master_templejt",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.mastertemplejt",
                        verbose_name="Originalni master templejt",
                    ),
                ),
                (
                    "odobrio",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Klijentski Dokument",
                "verbose_name_plural": "historical Klijentski Dokumenti",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalKontakt",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "ime_i_prezime",
                    models.CharField(max_length=255, verbose_name="Ime i prezime"),
                ),
                (
                    "pozicija",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Pozicija u firmi"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email adresa"),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "mobilni",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mobilni telefon"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primarni kontakt"),
                ),
                ("napomene", models.TextField(blank=True, verbose_name="Napomene")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.klijent",
                        verbose_name="Klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Kontakt",
                "verbose_name_plural": "historical Kontakti",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLekarskiPregled",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tip_pregleda",
                    models.CharField(
                        choices=[
                            ("Prethodni", "Prethodni"),
                            ("Periodični", "Periodični"),
                        ],
                        max_length=50,
                        verbose_name="Tip pregleda",
                    ),
                ),
                ("datum_pregleda", models.DateField(verbose_name="Datum pregleda")),
                (
                    "naredni_pregled",
                    models.DateField(verbose_name="Datum narednog pregleda"),
                ),
                (
                    "sposoban",
                    models.BooleanField(
                        default=True, verbose_name="Zdravstveno sposoban"
                    ),
                ),
                ("dokument", models.TextField(blank=True, max_length=100, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zaposleni",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.zaposleni",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lekarski Pregled",
                "verbose_name_plural": "historical Lekarski Pregledi",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLZO",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tip_opreme",
                    models.CharField(max_length=255, verbose_name="Tip opreme"),
                ),
                ("datum_izdavanja", models.DateField(verbose_name="Datum izdavanja")),
                (
                    "kolicina",
                    models.PositiveIntegerField(default=1, verbose_name="Količina"),
                ),
                (
                    "rok_trajanja",
                    models.DateField(
                        blank=True, null=True, verbose_name="Rok trajanja opreme"
                    ),
                ),
                (
                    "razduzeno",
                    models.BooleanField(default=False, verbose_name="Razduženo"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zaposleni",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.zaposleni",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lična Zaštitna Oprema (LZO)",
                "verbose_name_plural": "historical Lična Zaštitna Oprema (LZO)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMasterTemplejt",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv šablona"),
                ),
                (
                    "fajl",
                    models.TextField(max_length=100, verbose_name="Fajl templejta"),
                ),
                (
                    "verzija",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Verzija"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aktivan", "Aktivan"),
                            ("Arhiviran", "Arhiviran"),
                            ("U pripremi", "U pripremi"),
                        ],
                        default="Aktivan",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis i napomene")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kategorija",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.kategorijadokumenta",
                        verbose_name="Kategorija dokumenta",
                    ),
                ),
                (
                    "kreator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.mastertemplejt",
                        verbose_name="Prethodna verzija",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Master Templejt",
                "verbose_name_plural": "historical Master Templejti",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalObuka",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tip_obuke",
                    models.CharField(
                        choices=[
                            ("Inicijalna", "Inicijalna"),
                            ("Periodična", "Periodična"),
                            ("Vanredna", "Vanredna"),
                        ],
                        max_length=50,
                        verbose_name="Tip obuke",
                    ),
                ),
                ("datum_obuke", models.DateField(verbose_name="Datum obuke")),
                (
                    "datum_vazenja",
                    models.DateField(verbose_name="Datum važenja (naredna obuka)"),
                ),
                ("sertifikat", models.TextField(blank=True, max_length=100, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zaposleni",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.zaposleni",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Obuka BZR",
                "verbose_name_plural": "historical Obuke BZR",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOprema",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv opreme"),
                ),
                (
                    "inventarski_broj",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Inventarski broj"
                    ),
                ),
                (
                    "serijski_broj",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Serijski broj"
                    ),
                ),
                (
                    "proizvodjac",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Proizvođač"
                    ),
                ),
                (
                    "datum_nabavke",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum nabavke"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("U funkciji", "U funkciji"),
                            ("Na servisu", "Na servisu"),
                            ("Van upotrebe", "Van upotrebe"),
                        ],
                        default="U funkciji",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Oprema za Rad",
                "verbose_name_plural": "historical Oprema za Rad",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrganizacionaJedinica",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "naziv",
                    models.CharField(
                        max_length=255, verbose_name="Naziv poslovne jedinice"
                    ),
                ),
                ("adresa", models.CharField(max_length=255, verbose_name="Adresa")),
                (
                    "broj_zaposlenih",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Broj zaposlenih u jedinici"
                    ),
                ),
                (
                    "rukovodilac",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Rukovodilac jedinice"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.klijent",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Organizaciona Jedinica",
                "verbose_name_plural": "historical Organizacione Jedinice",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPoslatiMail",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("primaoci", models.TextField(verbose_name="Primaoci (To)")),
                (
                    "naslov",
                    models.CharField(max_length=255, verbose_name="Naslov email-a"),
                ),
                ("telo_poruke", models.TextField(verbose_name="Telo poruke")),
                (
                    "datum_slanja",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Datum slanja"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posiljalac",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Posiljalac",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Poslati Mail",
                "verbose_name_plural": "historical Poslati Mailovi",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPovredaNaRadu",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "datum_povrede",
                    models.DateTimeField(verbose_name="Datum i vreme povrede"),
                ),
                (
                    "mesto",
                    models.CharField(max_length=255, verbose_name="Mesto incidenta"),
                ),
                ("opis", models.TextField(verbose_name="Opis povrede i okolnosti")),
                ("svedoci", models.TextField(blank=True, verbose_name="Svedoci")),
                (
                    "tezina_povrede",
                    models.CharField(
                        choices=[
                            ("Laka", "Laka"),
                            ("Teška", "Teška"),
                            ("Smrtna", "Smrtna"),
                            ("Kolektivna", "Kolektivna"),
                        ],
                        max_length=20,
                        verbose_name="Težina povrede",
                    ),
                ),
                (
                    "izvestaj",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Izveštaj o povredi (fajl)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="U obradi", max_length=50, verbose_name="Status"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zaposleni",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.zaposleni",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Povreda na Radu",
                "verbose_name_plural": "historical Povrede na Radu",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPregledIspitivanje",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tip_pregleda",
                    models.CharField(
                        max_length=255, verbose_name="Tip pregleda/ispitivanja"
                    ),
                ),
                ("datum_pregleda", models.DateField(verbose_name="Datum pregleda")),
                (
                    "naredni_pregled",
                    models.DateField(verbose_name="Datum narednog pregleda"),
                ),
                (
                    "ovlascena_kuca",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ovlašćena kuća"
                    ),
                ),
                (
                    "nalaz",
                    models.CharField(
                        choices=[
                            ("Ispravan", "Ispravan"),
                            ("Neispravan", "Neispravan"),
                        ],
                        max_length=20,
                        verbose_name="Nalaz",
                    ),
                ),
                (
                    "strucni_nalaz_fajl",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Stručni nalaz (fajl)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oprema",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.oprema",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pregled i Ispitivanje",
                "verbose_name_plural": "historical Pregledi i Ispitivanja",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSmtpSettings",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("email_host", models.CharField(max_length=255)),
                ("email_port", models.IntegerField(default=587)),
                ("email_host_user", models.CharField(max_length=255)),
                ("email_host_password_encrypted", models.BinaryField()),
                ("email_use_tls", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical SMTP Podešavanje",
                "verbose_name_plural": "historical SMTP Podešavanja",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalZaposleni",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("ime", models.CharField(max_length=100, verbose_name="Ime")),
                ("prezime", models.CharField(max_length=100, verbose_name="Prezime")),
                (
                    "jmbg",
                    models.CharField(db_index=True, max_length=13, verbose_name="JMBG"),
                ),
                (
                    "radno_mesto",
                    models.CharField(max_length=255, verbose_name="Radno mesto"),
                ),
                (
                    "povecan_rizik",
                    models.BooleanField(
                        default=False, verbose_name="Radno mesto sa povećanim rizikom"
                    ),
                ),
                ("datum_zaposlenja", models.DateField(verbose_name="Datum zaposlenja")),
                (
                    "status",
                    models.CharField(
                        choices=[("Aktivan", "Aktivan"), ("Neaktivan", "Neaktivan")],
                        default="Aktivan",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "strucna_sprema",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stručna sprema"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "klijent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.klijent",
                    ),
                ),
                (
                    "organizaciona_jedinica",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.organizacionajedinica",
                        verbose_name="Organizaciona jedinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Zaposleni",
                "verbose_name_plural": "historical Zaposleni",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
